# Generated by Django 4.2.3 on 2023-07-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stackusers", "0002_profile_bio_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
