# Generated by Django 4.2.3 on 2023-07-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stackbase", "0003_alter_question_date_created_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.AddField(
            model_name="comment",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="stackbase.question",
            ),
            preserve_default=False,
        ),
    ]
