# Generated by Django 4.2.3 on 2023-07-21 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stackbase", "0004_remove_comment_user_comment_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="likes",
            field=models.ManyToManyField(
                related_name="question_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
